src/java/jsf/BookingController.java
package jsf;

import java.io.Serializable;
import java.util.Date;
import java.util.List;
import java.util.ResourceBundle;
import javax.ejb.EJB;
import javax.enterprise.context.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;
import javax.inject.Named;
import jpa.entities.Booking;
import jpa.session.BookingFacade;
import jsf.util.JsfUtil;
import jsf.util.PaginationHelper;

@Named("bookingController")
@SessionScoped
public class BookingController implements Serializable {

    private Booking current;
    private DataModel items = null;
    @EJB
    private jpa.session.BookingFacade ejbFacade;
    private PaginationHelper pagination;
    private int selectedItemIndex;

    public BookingController() {
    }

    public Booking getSelected() {
        if (current == null) {
            current = new Booking();
            selectedItemIndex = -1;
        }
        return current;
    }

    private BookingFacade getFacade() {
        return ejbFacade;
    }

    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(10) {

                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem() + getPageSize()}));
                }
            };
        }
        return pagination;
    }

    public String prepareList() {
        recreateModel();
        return "List";
    }

    public String prepareView() {
        current = (Booking) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "View";
    }

    public String prepareCreate() {
        current = new Booking();
        selectedItemIndex = -1;
        return "Create";
    }

    public String create() {
        if (current.getPickupDate().after(current.getDropoffDate())) {
            JsfUtil.addErrorMessage("Dönüş tarihi alış tarihinden sonra olmalı.");
            return null;
        } else if (vehicleIsReserved()) {
            JsfUtil.addErrorMessage("Seçtiğiniz araç o tarih alalığında tutulmuştur.");
            return null;
        } else {
            try {
                getFacade().create(current);
                JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("BookingCreated"));
                return prepareCreate();
            } catch (Exception e) {
                JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
                return null;
            }
        }
    }

    public String prepareEdit() {
        current = (Booking) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "Edit";
    }

    public String update() {
        if (current.getPickupDate().after(current.getDropoffDate())) {
            JsfUtil.addErrorMessage("Dönüş tarihi alış tarihinden sonra olmalı.");
            return null;
        } else if (vehicleIsReserved()) {
            JsfUtil.addErrorMessage("Seçtiğiniz araç o tarih alalığında tutulmuştur.");
            return null;
        } else {
            try {
                getFacade().edit(current);
                JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("BookingUpdated"));
                return "View";
            } catch (Exception e) {
                JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
                return null;
            }
        }
    }

    public String destroy() {
        current = (Booking) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        performDestroy();
        recreatePagination();
        recreateModel();
        return "List";
    }

    public String destroyAndView() {
        performDestroy();
        recreateModel();
        updateCurrentItem();
        if (selectedItemIndex >= 0) {
            return "View";
        } else {
            // all items were removed - go back to list
            recreateModel();
            return "List";
        }
    }
    
    public boolean vehicleIsReserved() {
        List<Booking> resultList = getFacade().findByVehicle(current);
        Date formMinDate = current.getPickupDate();
        Date formMaxDate = current.getDropoffDate();
        for (Booking b: resultList) {
            Date recordMinDate = b.getPickupDate();
            Date recordMaxDate = b.getDropoffDate();
            if ((afterOrEquals(formMinDate, recordMinDate) && beforeOrEquals(formMinDate, recordMaxDate)) // formMinDate record tarih aralığındaysa
             || (afterOrEquals(formMaxDate, recordMinDate) && beforeOrEquals(formMaxDate, recordMaxDate)) // veya formMaxDate record tarih aralığındaysa
             || (formMinDate.before(recordMinDate) && formMaxDate.after(recordMaxDate))) // veya form tarih aralığı record tarih aralığını kapsıyorsa
                return true; // araç dolu.
        }
        return false;
    }
    
    public boolean afterOrEquals(Date d1, Date d2) {
        return d1.after(d2) || d1.equals(d2);
    }
    
    public boolean beforeOrEquals(Date d1, Date d2) {
        return d1.before(d2) || d1.equals(d2);
    }

    private void performDestroy() {
        try {
            getFacade().remove(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("BookingDeleted"));
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
        }
    }

    private void updateCurrentItem() {
        int count = getFacade().count();
        if (selectedItemIndex >= count) {
            // selected index cannot be bigger than number of items:
            selectedItemIndex = count - 1;
            // go to previous page if last page disappeared:
            if (pagination.getPageFirstItem() >= count) {
                pagination.previousPage();
            }
        }
        if (selectedItemIndex >= 0) {
            current = getFacade().findRange(new int[]{selectedItemIndex, selectedItemIndex + 1}).get(0);
        }
    }

    public DataModel getItems() {
        if (items == null) {
            items = getPagination().createPageDataModel();
        }
        return items;
    }

    private void recreateModel() {
        items = null;
    }

    private void recreatePagination() {
        pagination = null;
    }

    public String next() {
        getPagination().nextPage();
        recreateModel();
        return "List";
    }

    public String previous() {
        getPagination().previousPage();
        recreateModel();
        return "List";
    }

    public SelectItem[] getItemsAvailableSelectMany() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), false);
    }

    public SelectItem[] getItemsAvailableSelectOne() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), true);
    }

    public Booking getBooking(java.lang.Integer id) {
        return ejbFacade.find(id);
    }

    @FacesConverter(forClass = Booking.class)
    public static class BookingControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            BookingController controller = (BookingController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "bookingController");
            return controller.getBooking(getKey(value));
        }

        java.lang.Integer getKey(String value) {
            java.lang.Integer key;
            key = Integer.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Integer value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Booking) {
                Booking o = (Booking) object;
                return getStringKey(o.getId());
            } else {
                throw new IllegalArgumentException("object " + object + " is of type " + object.getClass().getName() + "; expected type: " + Booking.class.getName());
            }
        }

    }

}

src/java/jsf/CampaignController.java
package jsf;

import jpa.entities.Campaign;
import jsf.util.JsfUtil;
import jsf.util.PaginationHelper;
import jpa.session.CampaignFacade;

import java.io.Serializable;
import java.util.ResourceBundle;
import javax.ejb.EJB;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;

@Named("campaignController")
@SessionScoped
public class CampaignController implements Serializable {

    private Campaign current;
    private DataModel items = null;
    @EJB
    private jpa.session.CampaignFacade ejbFacade;
    private PaginationHelper pagination;
    private int selectedItemIndex;

    public CampaignController() {
    }

    public Campaign getSelected() {
        if (current == null) {
            current = new Campaign();
            selectedItemIndex = -1;
        }
        return current;
    }

    private CampaignFacade getFacade() {
        return ejbFacade;
    }

    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(10) {

                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem() + getPageSize()}));
                }
            };
        }
        return pagination;
    }

    public String prepareList() {
        recreateModel();
        return "List";
    }

    public String prepareView() {
        current = (Campaign) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "View";
    }

    public String prepareCreate() {
        current = new Campaign();
        selectedItemIndex = -1;
        return "Create";
    }

    public String create() {
        try {
            getFacade().create(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("CampaignCreated"));
            return prepareCreate();
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String prepareEdit() {
        current = (Campaign) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "Edit";
    }

    public String update() {
        try {
            getFacade().edit(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("CampaignUpdated"));
            return "View";
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String destroy() {
        current = (Campaign) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        performDestroy();
        recreatePagination();
        recreateModel();
        return "List";
    }

    public String destroyAndView() {
        performDestroy();
        recreateModel();
        updateCurrentItem();
        if (selectedItemIndex >= 0) {
            return "View";
        } else {
            // all items were removed - go back to list
            recreateModel();
            return "List";
        }
    }

    private void performDestroy() {
        try {
            getFacade().remove(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("CampaignDeleted"));
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
        }
    }

    private void updateCurrentItem() {
        int count = getFacade().count();
        if (selectedItemIndex >= count) {
            // selected index cannot be bigger than number of items:
            selectedItemIndex = count - 1;
            // go to previous page if last page disappeared:
            if (pagination.getPageFirstItem() >= count) {
                pagination.previousPage();
            }
        }
        if (selectedItemIndex >= 0) {
            current = getFacade().findRange(new int[]{selectedItemIndex, selectedItemIndex + 1}).get(0);
        }
    }

    public DataModel getItems() {
        if (items == null) {
            items = getPagination().createPageDataModel();
        }
        return items;
    }

    private void recreateModel() {
        items = null;
    }

    private void recreatePagination() {
        pagination = null;
    }

    public String next() {
        getPagination().nextPage();
        recreateModel();
        return "List";
    }

    public String previous() {
        getPagination().previousPage();
        recreateModel();
        return "List";
    }

    public SelectItem[] getItemsAvailableSelectMany() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), false);
    }

    public SelectItem[] getItemsAvailableSelectOne() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), true);
    }

    public Campaign getCampaign(java.lang.Integer id) {
        return ejbFacade.find(id);
    }

    @FacesConverter(forClass = Campaign.class)
    public static class CampaignControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            CampaignController controller = (CampaignController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "campaignController");
            return controller.getCampaign(getKey(value));
        }

        java.lang.Integer getKey(String value) {
            java.lang.Integer key;
            key = Integer.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Integer value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Campaign) {
                Campaign o = (Campaign) object;
                return getStringKey(o.getId());
            } else {
                throw new IllegalArgumentException("object " + object + " is of type " + object.getClass().getName() + "; expected type: " + Campaign.class.getName());
            }
        }

    }

}

web/booking.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <body>
        <ui:composition template="#{userPreferences.themeLocation}">
            <ui:define name="main">
                <ui:component rendered="true">
                    <div id="booking">
                        <div class="formContent">
                            <h4>Üye girişi yaparak rezervasyon yapabilirsiniz.</h4>
                            <ui:include src="/partials/login_form.xhtml" />
                        </div>
                    </div>
                    <div id="application">
                        <div class="formContent">
                            <h4>Veya üye olmadan kiralama başvurusu yapabilirsiniz.</h4>
                            <ui:include src="/partials/application_form.xhtml" />
                        </div>
                    </div>
                </ui:component>
                <ui:component rendered="false">
                    <div class="content">
                        <h3>Rezervasyon</h3>
                        <h:form class="form">
                            <h:panelGrid columns="2">
                                <h:outputLabel value="Üye" for="clientId" />
                                <h:selectOneMenu id="clientId" value="#{bookingController.selected.clientId}" required="true" requiredMessage="#{bundle.CreateBookingRequiredMessage_clientId}">
                                    <f:selectItems value="#{clientController.itemsAvailableSelectOne}"/>
                                </h:selectOneMenu>
                                <h:outputLabel value="Araç" for="vehicleId" />
                                <h:selectOneMenu id="vehicleId" value="#{bookingController.selected.vehicleId}" required="true" requiredMessage="#{bundle.CreateBookingRequiredMessage_vehicleId}">
                                    <f:selectItems value="#{vehicleController.itemsAvailableSelectOne}"/>
                                </h:selectOneMenu>
                                <h:outputLabel value="Alış Tarihi" for="pickupDate" />
                                <h:inputText id="pickupDate" value="#{bookingController.selected.pickupDate}" required="true" requiredMessage="Alış tarihi gerekli.">
                                    <f:convertDateTime pattern="yyyy-MM-dd" />
                                </h:inputText>
                                <h:outputLabel value="Alış Yeri" for="pickupLocation" />
                                <h:inputText id="pickupLocation" value="#{bookingController.selected.pickupLocation}"/>
                                <h:outputLabel value="Dönüş Tarihi" for="dropoffDate" />
                                <h:inputText id="dropoffDate" value="#{bookingController.selected.dropoffDate}" required="true" requiredMessage="Dönüş tarihi gerekli.">
                                    <f:convertDateTime pattern="yyyy-MM-dd" />
                                </h:inputText>
                                <h:outputLabel value="Dönüş Yeri" for="dropffLocation" />
                                <h:inputText id="dropffLocation" value="#{bookingController.selected.dropffLocation}"/>
                                <h:outputLabel value="Toplam Fiyat" for="totalPrice" />
                                <h:inputText id="totalPrice" value="#{bookingController.selected.totalPrice}"/>
                                <h:outputLabel value="Açıklama" for="description" />
                                <h:inputTextarea rows="4" cols="30" id="description" value="#{bookingController.selected.description}"/>
                            </h:panelGrid>
                            <br />
                            <h:commandButton value="Rezervasyon Yap" action="#{bookingController.create}" />
                        </h:form>
                    </div>
                </ui:component>
            </ui:define>
        </ui:composition>
    </body>
</html>

web/campaigns.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:body>
        <ui:composition template="#{userPreferences.themeLocation}">
            <ui:define name="main">
                <h:form>
                    <h:panelGroup rendered="#{campaignController.items.rowCount > 0}">
                        <br/>
                        <div class="cmpPagination">
                        <h:outputText class="campaignPagination" value="#{campaignController.pagination.itemsCount} kampanya içerisinden #{campaignController.pagination.pageFirstItem + 1} ile #{campaignController.pagination.pageLastItem + 1} arası gösteriliyor"/>&nbsp;
                        <h:commandLink action="#{campaignController.publicPrevious()}" value="#{bundle.Previous} #{campaignController.pagination.pageSize}" rendered="#{campaignController.pagination.hasPreviousPage}"/>&nbsp;
                        <h:commandLink action="#{campaignController.publicNext()}" value="#{bundle.Next} #{campaignController.pagination.pageSize}" rendered="#{campaignController.pagination.hasNextPage}"/>&nbsp;
                       </div>
                        <br/>
                       <ui:repeat varStatus="status" value="#{campaignController.items}" var="item">
                            <div class="campaignRecord">
                                <div class="title">                                   
                                    <h4>Kampanya #{status.index+1}: #{item.title}</h4>
                                </div>
                                <div class="description">
                                   
                                    <p>#{item.description}</p>

                                </div>
                                <div class="footing">
                                    <h:panelGrid columns="2">
                                        <h:outputText value="#{bundle.ListCampaignTitle_beginDate} :"/>
                                        <h:outputText value="#{item.beginDate}"/>
                                        <h:outputText value="#{bundle.ListCampaignTitle_endDate}"/>
                                        <h:outputText value="#{item.endDate}"/>
                                    </h:panelGrid>
                                </div>
                                </div>
                           

                        </ui:repeat>
                    </h:panelGroup>


                </h:form>
            </ui:define>

        </ui:composition>

    </h:body>
</html>

web/contact.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>İletişim</title>
    </h:head>
    <body>
        <ui:composition template="#{userPreferences.themeLocation}">
            <ui:define name="main">
                <div class="content">
                    <h3>İletişim</h3>
                    <table class="contact">
                        <tr>
                            <td style="width: 400px;">
                                <h5>Adres:</h5>
                                <h5>Tel:</h5>
                                <h5>Faks:</h5>
                                <h5>Mail:</h5>
                            </td>
                            <td>
                                <iframe width="300" height="300" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/?ie=UTF8&amp;ll=37.0625,-95.677068&amp;spn=41.767874,79.013672&amp;t=h&amp;z=4&amp;output=embed"></iframe>
                            </td>
                        </tr>
                    </table>
                </div>
            </ui:define>
        </ui:composition>
    </body>
</html>

web/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>Ana Sayfa</title>
    </h:head>
    <body>
        <ui:composition template="#{userPreferences.themeLocation}">
            <ui:define name="main">
                <div id="left">
                    <ui:include src="/partials/search_form.xhtml" />
                    <ui:fragment rendered="#{userPreferences.isAdvancedTheme()}">
                        <div class="airportSabiha">
                            <div class="heading">
                                <h4>Sabiha Gökçen Havaalanı</h4>
                            </div>
                        </div>
                        <div class="airportAtatürk">
                            <div class="heading">
                                <h4>Atatürk Havaalanı</h4>
                            </div>
                        </div>
                    </ui:fragment>
                </div>
                <div id="rightContent">
                    <ui:fragment rendered="#{userPreferences.isAdvancedTheme()}">
                        <div class="fotorama" data-width="704" data-arrows="false" data-click="false" data-autoplay="3000" data-swipe="false" data-height="230" data-ratio="704/230" data-max-width="100%" data-allowfullscreen="false" data-stopautoplayontouch="false">
                            <h:graphicImage library="images" name="indexFotorama1.jpg"/>
                            <h:graphicImage library="images" name="indexFotorama1.jpg"/>
                            <h:graphicImage library="images" name="indexFotorama1.jpg"/>
                            <h:graphicImage library="images" name="indexFotorama1.jpg"/>
                        </div>
                    </ui:fragment>
                    
                </div>
            </ui:define>
        </ui:composition>
    </body>
</html>

web/login.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <body>
        <ui:composition template="./layouts/public.xhtml">
            <ui:define name="main">
                <div class="content">
                    <h3>Üye Girişi</h3>
                    <ui:include src="/partials/login_form.xhtml" />
                </div>
            </ui:define>
        </ui:composition>
    </body>
</html>

web/vehicles.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <body>
        <ui:composition template="#{userPreferences.themeLocation}">
            <ui:define name="main">
                <div id="left">
                    <ui:include src="/partials/search_form.xhtml" />
                </div>
                <div id="rightContent">
                    <h:form  rendered="#{vehicleController.items.rowCount > 0}">
                        <h:outputText class="pagination" value="  #{vehicleController.pagination.itemsCount} araç içinden #{vehicleController.pagination.pageFirstItem + 1}-#{vehicleController.pagination.pageLastItem + 1} arası gösteriliyor."/><br/>&nbsp;
                        <h:commandLink action="#{vehicleController.previousPublic}" value="#{bundle.Previous} #{vehicleController.pagination.pageSize}" rendered="#{vehicleController.pagination.hasPreviousPage}"/>&nbsp;
                        <h:commandLink action="#{vehicleController.nextPublic}" value="#{bundle.Next} #{vehicleController.pagination.pageSize}" rendered="#{vehicleController.pagination.hasNextPage}"/>&nbsp;
                        <ui:repeat value="#{vehicleController.items}" var="item">
                            <div class="vehicleRecord">
                                <div class="heading">#{item.title}</div>
                                <div class="options">
                                    Günlük Fiyat<br/>
                                    <div class="price">#{item.price} TL</div>
                                    <div class="buttons">
                                        <h:commandButton value="Aracı İncele" action="#{vehicleController.prepareViewPublic()}" />
                                        <h:commandButton value="Rezervasyon Yap" action="booking.xhtml"/>
                                    </div>
                                </div>
                                <div class="properties">
                                    <div class="image">
                                        <h:graphicImage library="images" name="/#{item.images}/vehicle1.jpg" width="180" height="100"/>
                                    </div>
                                    <table>
                                        <tr><td>Kategori:</td><td>#{item.category}</td><td>Yakıt Tipi:</td><td>#{item.fuel}</td></tr>
                                        <tr><td>Araç Yılı:</td><td>#{item.vyear}</td><td>Vites Tipi:</td><td>#{item.gear}</td></tr>
                                        <tr><td>Renk:</td><td>#{item.color}</td><td>Motor Hacmi:</td><td>#{item.engineVol}</td></tr>
                                    </table>
                                </div>
                            </div>
                        </ui:repeat>
                    </h:form>
                </div>
            </ui:define>
        </ui:composition>
    </body>
</html>